#!/bin/bash
#================================================================================
# Build the EXEC CICS WRITE DATASET stub
#================================================================================

_source_dir='src/main/cobol'
_testsource_dir='src/test/cobol'
_unittest_dir='src/test/cobol/unit-tests'
_resource_dir='src/test/resources'
_target_dir='target'
export COBCPY="$_source_dir/copybooks:$_unittest_dir"

cobuild --no-unit \
        --no-integration integration-tests \
        --target "$_target_dir" \
        "$_testsource_dir/convert-test.cbl"

cobuild --unitcopy convert-unit-tests \
        --integration integration-tests \
        --target "$_target_dir" \
        "$_source_dir/convert.cbl"
