#!/bin/bash
#================================================================================
# Build the EXEC CICS WRITE DATASET stub
#================================================================================

_source_dir='src/main/cobol'
_testsource_dir='src/test/cobol'
_unittest_dir='src/test/cobol/unit-tests'
_resource_dir='src/test/resources'
_target_dir='target'
export COBCPY="$_source_dir/copybooks:$_unittest_dir"

cobuild --unitcopy invdate-unit-tests \
        --no-integration \
        --target "$_target_dir" \
        "$_source_dir/invdate.cbl"
