#!/bin/bash
#================================================================================
# Build convert.cbl
#================================================================================

_source_dir='src/main/cobol'
_testsource_dir='src/test/cobol'
_unittest_dir='src/test/cobol/unit-tests'
_resource_dir='src/test/resources'
_target_dir='target'
export COBCPY="$_source_dir/copybooks:$_unittest_dir"

cobc -x "$_testsource_dir/convert-test.cbl"
#cobuild --no-unit \
#        --no-integration integration-tests \
#        "$_testsource_dir/convert-test.cbl"

cobuild --unitcopy convert-unit-tests \
        --integration integration-tests \
        --target "$_target_dir" \
        "$_source_dir/convert.cbl"
