#!/bin/bash
#================================================================================
# Run all the examples
#
#================================================================================

./run-ut SAMPLEC SAMPLE
./run-ut FIZZBUZC FIZZBUZZ
./run-ut CONVERTC CONVERT
./run-ut INVDATEC INVDATE
