#!/bin/bash
#================================================================================
# Run all the examples
#
#================================================================================

./run-ut SAMPLEC SAMPLE SAMPLET
./run-ut FIZZBUZC FIZZBUZZ FIZZBUZT
./run-ut CONVERTC CONVERT CONVERTT
./run-ut INVDATEC INVDATE INVDATET
./run-ut MOCKDEMC MOCKDEMO MOCKDEMT
./run-ut -s SUBPROGC SUBPROG SUBPROGT SUBPROGD
